package vault_test

import (
	"crypto/ecdsa"
	"crypto/sha256"
	"crypto/x509"
	"encoding/base64"
	"encoding/json"
	"os"
	"testing"

	"github.com/sh1ma/bwpk/internal/fido2"
	"github.com/sh1ma/bwpk/internal/vault"
)

// Using a synthetic vault (/tmp/bw_e2e_data.json, generated by node),
// exercise the full path: read data.json -> decrypt UserKey -> decrypt passkey ->
// sign assertion -> verify the signature with the public key.
//
// See /tmp/bw_e2e.mjs for generation. Skips if the file is absent.
func TestEndToEndAssertion(t *testing.T) {
	const dataPath = "/tmp/bw_e2e_data.json"
	const metaPath = "/tmp/bw_e2e_meta.json"
	if _, err := os.Stat(dataPath); err != nil {
		t.Skip("synthetic vault not generated (run: node /tmp/bw_e2e.mjs)")
	}
	metaB, err := os.ReadFile(metaPath)
	if err != nil {
		t.Skip("meta not generated")
	}
	var meta struct {
		Password string `json:"password"`
		RpID     string `json:"rpId"`
		CredID   string `json:"credId"`
		SpkiB64  string `json:"spkiB64"`
	}
	if err := json.Unmarshal(metaB, &meta); err != nil {
		t.Fatal(err)
	}

	v, err := vault.Open(dataPath)
	if err != nil {
		t.Fatal(err)
	}
	userKey, err := v.Unlock(meta.Password)
	if err != nil {
		t.Fatalf("Unlock failed: %v", err)
	}
	pks, err := v.Passkeys(userKey, meta.RpID)
	if err != nil {
		t.Fatal(err)
	}
	if len(pks) != 1 {
		t.Fatalf("unexpected number of passkeys: %d", len(pks))
	}
	pk := pks[0]
	if pk.CredentialID != meta.CredID {
		t.Fatalf("credentialId mismatch: %s != %s", pk.CredentialID, meta.CredID)
	}
	if pk.RpID != "example.com" || pk.UserName != "alice" || !pk.Discoverable {
		t.Fatalf("decrypted fields are invalid: %+v", pk)
	}

	// private key -> assertion
	der, err := vault.DecodeKeyValue(pk.KeyValue)
	if err != nil {
		t.Fatal(err)
	}
	priv, err := fido2.ParsePKCS8ECDSA(der)
	if err != nil {
		t.Fatal(err)
	}

	clientData := []byte(`{"type":"webauthn.get","challenge":"AAAA","origin":"https://example.com"}`)
	clientDataHash := sha256.Sum256(clientData)
	authData, err := fido2.GenerateAuthData(fido2.AuthDataParams{
		RpID: pk.RpID, Counter: uint32(pk.Counter), UserPresence: true, UserVerified: true,
	})
	if err != nil {
		t.Fatal(err)
	}
	sig, err := fido2.Sign(authData, clientDataHash[:], priv)
	if err != nil {
		t.Fatal(err)
	}

	// verify the signature with the public key (SPKI) emitted by node
	spki, _ := base64.StdEncoding.DecodeString(meta.SpkiB64)
	pubAny, err := x509.ParsePKIXPublicKey(spki)
	if err != nil {
		t.Fatal(err)
	}
	pub := pubAny.(*ecdsa.PublicKey)

	// the signed digest is SHA256(authData||clientDataHash)
	sigBase := append(append([]byte{}, authData...), clientDataHash[:]...)
	digest := sha256.Sum256(sigBase)
	if !ecdsa.VerifyASN1(pub, digest[:], sig) {
		t.Fatal("assertion signature verification failed")
	}

	// minimal authData structure check: rpIdHash(32)+flags(1)+counter(4) = 37 bytes (no attestation)
	if len(authData) != 37 {
		t.Fatalf("invalid authData length: %d", len(authData))
	}
	rpHash := sha256.Sum256([]byte("example.com"))
	if string(authData[:32]) != string(rpHash[:]) {
		t.Fatal("rpIdHash mismatch")
	}
	// flags: UP|UV|BE|BS = 0x1D
	if authData[32] != 0x1D {
		t.Fatalf("invalid flags: 0x%02x", authData[32])
	}
}
